crime_data <- read.table("C:/Users/Amita Kamat/Documents/R/crime.dat", header=T, sep="\t")
max_y <- max(crime_data)
colors <- c("blue","red","darkgreen", "black")
png(filename="C:/Users/Amita Kamat/Documents/R/crime-analysis.png", height=1000, width=1000, bg="white")
plot(crime_data$On.Campus, type="o", col=colors[1],  ylim=c(0,max_y), axes=FALSE, ann=FALSE, lwd=3)
axis(1, at=1:3, lab=c("2014", "2015", "2016"))
axis(2, las=1, at=20*0:max_y)
lines(crime_data$Student.Housing, type="o", pch=22, lty=2, col=colors[2], lwd=3)
lines(crime_data$Non.Campus, type="o", pch=23, lty=3,  col=colors[3], lwd=3)
lines(crime_data$Public.Property, type="o", pch=24, lty=4,  col=colors[4], lwd=3)
title(xlab= "Year", col.lab=rgb(0,0.5,0))
title(ylab= "Total Arrests", col.lab=rgb(0,0.5,0))
legend(1, max_y, names(crime_data), cex=0.8, col=colors,  pch=21:24, lty=1:4);
dev.off()
